/**
 * Microsoft 365 synthetic data (logs + metrics) lives under `src/m365/`.
 * The Azure app surfaces these services in the same wizard as Azure Monitor sources,
 * matching how Elastic bundles Microsoft 365 with Azure integrations.
 */

/** Azure service IDs whose metrics are generated by `src/m365/generators/metrics/`. */
export const M365_METRIC_SERVICE_IDS_FOR_AZURE = new Set([
  "active-users-services",
  "teams-user-activity",
  "outlook-activity",
  "onedrive-usage-storage",
]);

/** Maps Azure UI service IDs to Elastic integration identifiers for M365 metrics templates. */
export const M365_AZURE_METRICS_INTEGRATION_BY_SERVICE_ID: Record<string, "o365_metrics"> = {
  "active-users-services": "o365_metrics",
  "teams-user-activity": "o365_metrics",
  "outlook-activity": "o365_metrics",
  "onedrive-usage-storage": "o365_metrics",
};
