/**
 * METRICS_GENERATORS — map of service ID → dimensional metric generator.
 *
 * Each generator signature: (ts: string, er: number) => Object[]
 *   ts  - ISO timestamp string
 *   er  - error rate in [0, 1]
 *   returns an array of per-dimension CloudWatch metric documents
 *
 * Document shape (Elastic AWS integration format):
 * {
 *   "@timestamp": "<iso>",
 *   "cloud":      { provider, region, account },
 *   "aws": { "<service>": { metrics: {...}, dimensions: {...} } },
 *   "metricset":  { name: "<service>", period: 60000 },
 *   "data_stream":{ type: "metrics", dataset: "aws.<service>", namespace: "default" },
 *   "event":      { dataset: "aws.<service>", module: "aws" },
 * }
 */

// ─── Compute ──────────────────────────────────────────────────────────────────
import {
  generateLambdaMetrics,
  generateEc2Metrics,
  generateEcsMetrics,
  generateFargateMetrics,
  generateEksMetrics,
  generateApprunnerMetrics,
  generateBatchMetrics,
  generateElasticbeanstalkMetrics,
  generateEcrMetrics,
} from "./compute.js";

// ─── Networking ───────────────────────────────────────────────────────────────
import {
  generateAlbMetrics,
  generateNlbMetrics,
  generateApigatewayMetrics,
  generateCloudfrontMetrics,
  generateNatgatewayMetrics,
  generateTransitgatewayMetrics,
  generateVpnMetrics,
  generateNetworkfirewallMetrics,
  generateGlobalacceleratorMetrics,
  generateDirectconnectMetrics,
  generateVpcMetrics,
  generatePrivatelinkMetrics,
} from "./networking.js";

// ─── Databases & storage ──────────────────────────────────────────────────────
import {
  generateRdsMetrics,
  generateAuroraMetrics,
  generateDynamodbMetrics,
  generateElasticacheMetrics,
  generateRedshiftMetrics,
  generateS3Metrics,
  generateDocdbMetrics,
  generateOpensearchMetrics,
  generateNeptuneMetrics,
  generateKeyspacesMetrics,
  generateMemorydbMetrics,
  generateEbsMetrics,
  generateEfsMetrics,
  generateTimestreamMetrics,
  generateBackupMetrics,
  generateFsxMetrics,
  generateStoragelensMetrics,
  generateDatasyncMetrics,
  generateStoragegatewayMetrics,
  generateQldbMetrics,
} from "./databases.js";

// ─── Streaming & messaging ────────────────────────────────────────────────────
import {
  generateSqsMetrics,
  generateKinesisMetrics,
  generateMskMetrics,
  generateSnsMetrics,
  generateFirehoseMetrics,
  generateEventbridgeMetrics,
  generateAmazonmqMetrics,
  generateKinesisanalyticsMetrics,
} from "./streaming.js";

// ─── Analytics & AI / ML ─────────────────────────────────────────────────────
import {
  generateGlueMetrics,
  generateEmrMetrics,
  generateAthenaMetrics,
  generateSagemakerMetrics,
  generateBedrockMetrics,
  generateBedrockagentMetrics,
  generateRekognitionMetrics,
  generateTextractMetrics,
  generateTranscribeMetrics,
  generateTranslateMetrics,
  generatePollyMetrics,
  generateComprehendMetrics,
  generateLexMetrics,
  generateForecastMetrics,
  generatePersonalizeMetrics,
  generateLookoutmetricsMetrics,
  generateLakeformationMetrics,
  generateQuicksightMetrics,
  generateAppflowMetrics,
  generateDatabrewMetrics,
  generateXrayMetrics,
  generateSesMetrics,
} from "./analytics.js";

// ─── Security & management ────────────────────────────────────────────────────
import {
  generateWafMetrics,
  generateWafv2Metrics,
  generateShieldMetrics,
  generateKmsMetrics,
  generateCognitoMetrics,
  generateGuarddutyMetrics,
  generateCloudwatchMetrics,
  generateStepfunctionsMetrics,
  generateSsmMetrics,
  generateCloudformationMetrics,
  generateCodebuildMetrics,
  generateCodepipelineMetrics,
  generateCodedeployMetrics,
  generateAmplifyMetrics,
  generateAutoscalingMetrics,
  generateRoute53Metrics,
  generateBillingMetrics,
  generateHealthMetrics,
  generateInspectorMetrics,
  generateMacieMetrics,
  generateConfigMetrics,
  generateAccessanalyzerMetrics,
  generateIotcoreMetrics,
  generateWorkspacesMetrics,
  generateConnectMetrics,
  generateGameliftMetrics,
  generateSecretsmanagerMetrics,
  generateAcmMetrics,
  generateCloudtrailMetrics,
  generateAppsyncMetrics,
  generateTrustedadvisorMetrics,
  generateImagebuilderMetrics,
  generateDevopsgouruMetrics,
  generatePinpointMetrics,
  generateTransferfamilyMetrics,
  generateLightsailMetrics,
  generateRamMetrics,
  generateDmsMetrics,
  generateCodecommitMetrics,
  generateCodeartifactMetrics,
  generateSecurityhubMetrics,
} from "./security.js";

// ─── Generic fallback ─────────────────────────────────────────────────────────
import { makeGenericGenerator } from "./generic.js";
import { ELASTIC_METRICS_DATASET_MAP, ELASTIC_DATASET_MAP } from "../../../data/elasticMaps";

function dataset(
  svcId: keyof typeof ELASTIC_METRICS_DATASET_MAP | keyof typeof ELASTIC_DATASET_MAP | string
) {
  const m = ELASTIC_METRICS_DATASET_MAP[svcId as keyof typeof ELASTIC_METRICS_DATASET_MAP];
  const d = ELASTIC_DATASET_MAP[svcId as keyof typeof ELASTIC_DATASET_MAP];
  return m ?? d ?? `aws.${svcId}`;
}

const GENERIC_SERVICE_IDS = [
  "iotanalytics",
  "iotevents",
  "iotsitewise",
  "iotdefender",
  "controltower",
  "organizations",
  "servicecatalog",
  "servicequotas",
  "computeoptimizer",
  "budgets",
  "resiliencehub",
  "migrationhub",
  "identitycenter",
  "detective",
  "verifiedaccess",
  "securitylake",
  "mediaconvert",
  "medialive",
  "managedblockchain",
  "frauddetector",
  "locationservice",
  "appstream",
  "codeguru",
  "qbusiness",
  "comprehendmedical",
  "networkmanager",
  "vpcipam",
  "private5g",
  "neptuneanalytics",
  "auroradsql",
  "mainframemodernization",
  "parallelcomputing",
  "evs",
  "simspaceweaver",
  "healthomics",
  "bedrockdataautomation",
  "groundstation",
  "workmail",
  "wickr",
  "qdeveloper",
  "endusermessaging",
  // v11.5 new services
  "lookoutequipment",
  "monitron",
  "networkaccessanalyzer",
  "incidentmanager",
  "cloudshell",
  "cloud9",
  "robomaker",
  "kinesisvideo",
  "panorama",
  "freertos",
  "cloudwatchrum",
  // v12.0 — services with confirmed CloudWatch metric emission
  "vpclattice",
  "mskconnect",
  "mwaa",
  "kendra",
  "iottwinmaker",
  "iotfleetwise",
  "fis",
  "managedgrafana",
  "appconfig",
  "cleanrooms",
  "healthlake",
  "deadlinecloud",
  "licensemanager",
];

const GENERIC_GENERATORS = Object.fromEntries(
  GENERIC_SERVICE_IDS.map((id) => [id, makeGenericGenerator(id, dataset(id))])
);

// ─── Full registry ────────────────────────────────────────────────────────────
export const METRICS_GENERATORS = {
  // Compute
  lambda: generateLambdaMetrics,
  ec2: generateEc2Metrics,
  ecs: generateEcsMetrics,
  fargate: generateFargateMetrics,
  eks: generateEksMetrics,
  apprunner: generateApprunnerMetrics,
  batch: generateBatchMetrics,
  elasticbeanstalk: generateElasticbeanstalkMetrics,
  ecr: generateEcrMetrics,

  // Networking
  alb: generateAlbMetrics,
  nlb: generateNlbMetrics,
  apigateway: generateApigatewayMetrics,
  cloudfront: generateCloudfrontMetrics,
  natgateway: generateNatgatewayMetrics,
  transitgateway: generateTransitgatewayMetrics,
  vpn: generateVpnMetrics,
  networkfirewall: generateNetworkfirewallMetrics,
  globalaccelerator: generateGlobalacceleratorMetrics,
  directconnect: generateDirectconnectMetrics,
  vpc: generateVpcMetrics,
  privatelink: generatePrivatelinkMetrics,

  // Databases & storage
  rds: generateRdsMetrics,
  aurora: generateAuroraMetrics,
  dynamodb: generateDynamodbMetrics,
  elasticache: generateElasticacheMetrics,
  redshift: generateRedshiftMetrics,
  s3: generateS3Metrics,
  docdb: generateDocdbMetrics,
  opensearch: generateOpensearchMetrics,
  neptune: generateNeptuneMetrics,
  keyspaces: generateKeyspacesMetrics,
  memorydb: generateMemorydbMetrics,
  ebs: generateEbsMetrics,
  efs: generateEfsMetrics,
  timestream: generateTimestreamMetrics,
  backup: generateBackupMetrics,
  fsx: generateFsxMetrics,
  storagelens: generateStoragelensMetrics,
  datasync: generateDatasyncMetrics,
  storagegateway: generateStoragegatewayMetrics,
  qldb: generateQldbMetrics,

  // Streaming & messaging
  sqs: generateSqsMetrics,
  kinesis: generateKinesisMetrics,
  msk: generateMskMetrics,
  sns: generateSnsMetrics,
  firehose: generateFirehoseMetrics,
  eventbridge: generateEventbridgeMetrics,
  amazonmq: generateAmazonmqMetrics,
  kinesisanalytics: generateKinesisanalyticsMetrics,

  // Analytics & AI / ML
  glue: generateGlueMetrics,
  emr: generateEmrMetrics,
  athena: generateAthenaMetrics,
  sagemaker: generateSagemakerMetrics,
  bedrock: generateBedrockMetrics,
  bedrockagent: generateBedrockagentMetrics,
  rekognition: generateRekognitionMetrics,
  textract: generateTextractMetrics,
  transcribe: generateTranscribeMetrics,
  translate: generateTranslateMetrics,
  polly: generatePollyMetrics,
  comprehend: generateComprehendMetrics,
  lex: generateLexMetrics,
  forecast: generateForecastMetrics,
  personalize: generatePersonalizeMetrics,
  lookoutmetrics: generateLookoutmetricsMetrics,
  lakeformation: generateLakeformationMetrics,
  quicksight: generateQuicksightMetrics,
  appflow: generateAppflowMetrics,
  databrew: generateDatabrewMetrics,
  xray: generateXrayMetrics,
  ses: generateSesMetrics,

  // Security & management
  waf: generateWafMetrics,
  wafv2: generateWafv2Metrics,
  shield: generateShieldMetrics,
  kms: generateKmsMetrics,
  cognito: generateCognitoMetrics,
  guardduty: generateGuarddutyMetrics,
  cloudwatch: generateCloudwatchMetrics,
  stepfunctions: generateStepfunctionsMetrics,
  ssm: generateSsmMetrics,
  cloudformation: generateCloudformationMetrics,
  codebuild: generateCodebuildMetrics,
  codepipeline: generateCodepipelineMetrics,
  codedeploy: generateCodedeployMetrics,
  amplify: generateAmplifyMetrics,
  autoscaling: generateAutoscalingMetrics,
  route53: generateRoute53Metrics,
  billing: generateBillingMetrics,
  health: generateHealthMetrics,
  inspector: generateInspectorMetrics,
  macie: generateMacieMetrics,
  config: generateConfigMetrics,
  accessanalyzer: generateAccessanalyzerMetrics,
  iotcore: generateIotcoreMetrics,
  workspaces: generateWorkspacesMetrics,
  connect: generateConnectMetrics,
  gamelift: generateGameliftMetrics,
  secretsmanager: generateSecretsmanagerMetrics,
  acm: generateAcmMetrics,
  cloudtrail: generateCloudtrailMetrics,
  appsync: generateAppsyncMetrics,
  trustedadvisor: generateTrustedadvisorMetrics,
  imagebuilder: generateImagebuilderMetrics,
  devopsguru: generateDevopsgouruMetrics,
  pinpoint: generatePinpointMetrics,
  transferfamily: generateTransferfamilyMetrics,
  lightsail: generateLightsailMetrics,
  ram: generateRamMetrics,
  dms: generateDmsMetrics,
  codecommit: generateCodecommitMetrics,
  codeartifact: generateCodeartifactMetrics,
  securityhub: generateSecurityhubMetrics,

  greengrass: makeGenericGenerator("greengrass", "aws.greengrass"),
  ...GENERIC_GENERATORS,
  // v11.0 — services with meaningful CloudWatch metrics
  wavelength: makeGenericGenerator("wavelength", "aws.wavelength"),
  nova: makeGenericGenerator("nova", "aws.nova"),
  lookoutvision: makeGenericGenerator("lookoutvision", "aws.lookoutvision"),
  appmesh: makeGenericGenerator("appmesh", "aws.appmesh"),
  clientvpn: makeGenericGenerator("clientvpn", "aws.clientvpn"),
  cloudmap: makeGenericGenerator("cloudmap", "aws.cloudmap"),
  outposts: makeGenericGenerator("outposts", "aws.outposts"),
  verifiedpermissions: makeGenericGenerator("verifiedpermissions", "aws.verifiedpermissions"),
  dax: makeGenericGenerator("dax", "aws.dax"),
  chimesdkvoice: makeGenericGenerator("chimesdkvoice", "aws.chimesdkvoice"),
  drs: makeGenericGenerator("drs", "aws.drs"),
};
