/**
 * Trace scenario metadata for the GCP load generator UI.
 */

export const GCP_TRACE_SERVICES = [
  {
    id: "cloud-functions",
    label: "Cloud Functions",
    desc: "HTTP-triggered function with downstream calls",
    icon: "ƒ",
    group: "Serverless",
  },
  {
    id: "cloud-run",
    label: "Cloud Run",
    desc: "Container service handling HTTP requests",
    icon: "▷",
    group: "Serverless",
  },
  {
    id: "gke",
    label: "GKE",
    desc: "Kubernetes pod-to-pod service mesh",
    icon: "☸",
    group: "Containers",
  },
  {
    id: "app-engine",
    label: "App Engine",
    desc: "Web app request with datastore calls",
    icon: "⊙",
    group: "Serverless",
  },
  {
    id: "cloud-spanner",
    label: "Cloud Spanner",
    desc: "Distributed transaction across regions",
    icon: "⟐",
    group: "Database",
  },
  {
    id: "pubsub",
    label: "Pub/Sub",
    desc: "Async message publish and process pipeline",
    icon: "◉",
    group: "Messaging",
  },
  {
    id: "bigquery",
    label: "BigQuery",
    desc: "Analytical query with stage execution",
    icon: "◇",
    group: "Analytics",
  },
  {
    id: "workflow-ecommerce",
    label: "E-Commerce Order",
    desc: "Cloud Run → Spanner → Pub/Sub → Cloud Functions pipeline",
    icon: "⛓",
    group: "Workflows",
  },
  {
    id: "workflow-ml",
    label: "ML Inference",
    desc: "Cloud Run → Vertex AI → BigQuery pipeline",
    icon: "✦",
    group: "Workflows",
  },
  {
    id: "workflow-data",
    label: "Data Pipeline",
    desc: "Pub/Sub → Dataflow → BigQuery → Cloud Storage export",
    icon: "⟿",
    group: "Workflows",
  },
  {
    id: "cloud-sql",
    label: "Cloud SQL",
    desc: "Multi-step SQL query with connection pooling",
    icon: "⊞",
    group: "Database",
  },
  {
    id: "dataflow",
    label: "Dataflow",
    desc: "Beam pipeline stage with source/transform/sink",
    icon: "⟿",
    group: "Analytics",
  },
  {
    id: "vertex-ai",
    label: "Vertex AI",
    desc: "Model inference with preprocessing and GPU execution",
    icon: "✦",
    group: "AI/ML",
  },
  {
    id: "firestore",
    label: "Firestore",
    desc: "Multi-document transaction with reads and writes",
    icon: "⊙",
    group: "Database",
  },
  {
    id: "workflow-cascading",
    label: "Cascading Failure",
    desc: "API Gateway → Cloud Run → SQL timeout → DLQ chain",
    icon: "⚡",
    group: "Workflows",
  },
  {
    id: "workflow-pubsub-fanout",
    label: "Pub/Sub fan-out",
    desc: "Cloud Run → Pub/Sub publish → parallel Cloud Functions, Cloud Run, and BigQuery consumers",
    icon: "◎",
    group: "Workflows",
  },
  {
    id: "workflow-gcs-pipeline",
    label: "GCS → Functions → BigQuery",
    desc: "GCS object notification → Pub/Sub → Cloud Function → BigQuery load (data lake promote)",
    icon: "⬦",
    group: "Workflows",
  },
  {
    id: "workflow-eventarc-orchestration",
    label: "Eventarc → Workflows → Cloud Run",
    desc: "Eventarc audit trigger → Cloud Workflows execution → stepped Cloud Run (Spanner, Cloud SQL, Pub/Sub)",
    icon: "⎈",
    group: "Workflows",
  },
  {
    id: "cloud-storage",
    label: "Cloud Storage",
    desc: "GCS object operations — GetObject/PutObject/CopyObject with downstream metadata spans",
    icon: "🗄",
    group: "Single-Service",
  },
  {
    id: "compute-engine",
    label: "Compute Engine",
    desc: "VM lifecycle operations — instance start/stop/restart via Compute API spans",
    icon: "⬡",
    group: "Single-Service",
  },
  {
    id: "apigee",
    label: "Apigee API Gateway",
    desc: "API proxy request chain — quota + auth + backend spans",
    icon: "⊕",
    group: "Single-Service",
  },
  {
    id: "cloud-build",
    label: "Cloud Build",
    desc: "Build pipeline — sequential step spans (pull → install → test → build → push)",
    icon: "⚙",
    group: "Single-Service",
  },
  {
    id: "gemini",
    label: "Gemini AI",
    desc: "Model inference — generateContent/embedContent with optional RAG retrieval spans",
    icon: "✦",
    group: "Single-Service",
  },
  {
    id: "alloydb",
    label: "AlloyDB",
    desc: "PostgreSQL-compatible queries — connect, execute, and fetch spans",
    icon: "✦",
    group: "Database",
  },
  {
    id: "bigtable",
    label: "Bigtable",
    desc: "Wide-column reads, mutations, and sampling spans",
    icon: "≡",
    group: "Database",
  },
  {
    id: "memorystore",
    label: "Memorystore (Redis)",
    desc: "Redis command spans from application-side caching",
    icon: "⚡",
    group: "Database",
  },
  {
    id: "cloud-tasks",
    label: "Cloud Tasks",
    desc: "Task enqueue and worker execution spans",
    icon: "☰",
    group: "Serverless",
  },
  {
    id: "cloud-scheduler",
    label: "Cloud Scheduler",
    desc: "Scheduled job tick and HTTP target invocation spans",
    icon: "⏱",
    group: "Serverless",
  },
  {
    id: "composer",
    label: "Cloud Composer",
    desc: "Airflow DAG task execution chain",
    icon: "⟿",
    group: "Analytics",
  },
  {
    id: "dataproc",
    label: "Dataproc",
    desc: "Spark job stage spans on a managed cluster",
    icon: "⚙",
    group: "Analytics",
  },
  {
    id: "cloud-run-jobs",
    label: "Cloud Run jobs",
    desc: "Batch job bootstrap, process, and finalize spans",
    icon: "▷",
    group: "Serverless",
  },
  {
    id: "dialogflow",
    label: "Dialogflow",
    desc: "DetectIntent, fulfillment webhook, and Agent Assist search spans",
    icon: "◯",
    group: "AI/ML",
  },
  {
    id: "cloud-armor",
    label: "Cloud Armor",
    desc: "Security policy evaluation and protected backend request spans",
    icon: "◈",
    group: "Networking",
  },
];
