/**
 * GCP_METRICS_GENERATORS — map of service ID → dimensional metric generator.
 *
 * Each generator: (ts: string, er: number) => EcsDocument[]
 *   ts — ISO timestamp string
 *   er — error rate in [0, 1]
 *
 * Each document is one Cloud Monitoring time series (metric + resource + point).
 */

import { GCP_METRICS_SUPPORTED_SERVICE_IDS } from "../../data/elasticMaps.js";
import type { MetricGenerator } from "../../../aws/generators/types.js";
import { generateComputeEngineMetrics, generateGkeMetrics } from "./compute.js";
import {
  generateCloudLbMetrics,
  generateCloudCdnMetrics,
  generateCloudDnsMetrics,
  generateCloudArmorMetrics,
  generateCloudInterconnectMetrics,
  generateCloudNatMetrics,
  generateCloudVpnMetrics,
  generateCloudRouterMetrics,
  generateVpcFlowMetrics,
  generateCloudKmsMetrics,
  generateSecretManagerMetrics,
  generateCloudIdsMetrics,
  generateBinaryAuthorizationMetrics,
  generateCertificateAuthorityMetrics,
  generateIdentityAwareProxyMetrics,
  generateWebSecurityScannerMetrics,
  generateWebRiskMetrics,
  generateRecaptchaEnterpriseMetrics,
} from "./networking.js";
import {
  generateCloudSqlMetrics,
  generateCloudSpannerMetrics,
  generateBigtableMetrics,
  generateFirestoreMetrics,
  generateAlloyDbMetrics,
  generateMemorystoreMetrics,
} from "./databases.js";
import { generatePubSubMetrics, generateDataflowMetrics } from "./streaming.js";
import {
  generateBigQueryMetrics,
  generateDataprocMetrics,
  generateComposerMetrics,
  generateDataCatalogMetrics,
  generateDataFusionMetrics,
  generateDatabaseMigrationMetrics,
  generateDataplexMetrics,
  generateDatastreamMetrics,
  generateAnalyticsHubMetrics,
  generateLookerMetrics,
  generateNaturalLanguageMetrics,
  generateSpeechToTextMetrics,
  generateTextToSpeechMetrics,
  generateTranslationMetrics,
  generateVideoIntelligenceMetrics,
  generateVisionAiMetrics,
  generateRecommendationsAiMetrics,
  generateRetailApiMetrics,
  generateDocumentAiMetrics,
  generateHealthcareApiMetrics,
  generateDialogflowMetrics,
  generateContactCenterAiMetrics,
} from "./analytics.js";
import { mergeGcpMetricVariants } from "../mergeHelpers.js";
import {
  generateCloudFunctionsMetrics,
  generateCloudRunMetrics,
  generateAppEngineMetrics,
  generateCloudTasksMetrics,
} from "./serverless.js";
import { generateCloudStorageMetrics } from "./storage.js";
import { generateVertexAiMetrics, generateGeminiMetrics } from "./aiml.js";
import {
  generateCloudRunJobsMetrics,
  generateCloudSchedulerMetrics,
  generateCloudTpuMetrics,
  generateCloudWorkstationsMetrics,
  generateBatchMetrics,
  generateDeploymentManagerMetrics,
  generateEventarcMetrics,
  generateWorkflowsMetrics,
  generateFirebaseMetrics,
  generateCloudEndpointsMetrics,
  generateApiGatewayMetrics,
  generateApplicationIntegrationMetrics,
  generateServerlessVpcAccessMetrics,
  generateServiceDirectoryMetrics,
  generatePrivateServiceConnectMetrics,
  generateNetworkConnectivityCenterMetrics,
  generateNetworkIntelligenceCenterMetrics,
  generateTrafficDirectorMetrics,
  generateCloudAuditLogsMetrics,
} from "./platform.js";
import {
  generateCloudDeployMetrics,
  generateCloudLoggingMetrics,
  generateCloudMonitoringMetrics,
  generateCloudIdentityMetrics,
  generateIamMetrics,
  generateOrgPolicyMetrics,
  generateResourceManagerMetrics,
  generateEssentialContactsMetrics,
  generateErrorReportingMetrics,
  generateAssuredWorkloadsMetrics,
  generateContainerRegistryMetrics,
  generateArtifactRegistryMetrics,
  generateDlpMetrics,
  generateAnthosMetrics,
  generateAnthosConfigMgmtMetrics,
  generateAnthosServiceMeshMetrics,
  generateMigrateToContainersMetrics,
  generateSecurityCommandCenterMetrics,
  generateSecurityOperationsMetrics,
  generateManagedAdMetrics,
} from "./governance.js";
import {
  generatePubsubLiteMetrics,
  generatePersistentDiskMetrics,
  generateFilestoreMetrics,
  generateCloudBuildMetrics,
  generateIotCoreMetrics,
  generateGkeEnterpriseMetrics,
  generateAutomlMetrics,
  generateAccessContextManagerMetrics,
  generateActiveAssistMetrics,
  generateApigeeMetrics,
  generateBackupDrMetrics,
  generateBareMetalMetrics,
  generateBeyondcorpMetrics,
  generateBillingMetrics,
  generateCloudAssetInventoryMetrics,
  generateCloudDomainsMetrics,
  generateMediaCdnMetrics,
  generateTranscoderMetrics,
  generateVertexAiWorkbenchMetrics,
  generateVertexAiPipelinesMetrics,
  generateVertexAiFeatureStoreMetrics,
  generateVertexAiMatchingEngineMetrics,
  generateVertexAiTensorboardMetrics,
  generateVmwareEngineMetrics,
} from "./remaining.js";
import {
  generateSoleTenantNodesMetrics,
  generateSpotVmsMetrics,
  generateShieldedVmsMetrics,
  generateConfidentialComputingMetrics,
  generateMigrateToVmsMetrics,
  generateConfigConnectorMetrics,
  generatePacketMirroringMetrics,
  generateNetworkServiceTiersMetrics,
  generateServerlessNegMetrics,
  generateStorageTransferMetrics,
  generateVertexAiSearchMetrics,
  generateSourceRepositoriesMetrics,
  generateCloudTraceMetrics,
  generateCloudProfilerMetrics,
  generateApiHubMetrics,
} from "./variants.js";
import {
  generateVertexAiAgentBuilderMetrics,
  generateColabEnterpriseMetrics,
  generateDistributedCloudMetrics,
  generateParallelstoreMetrics,
  generateDataformMetrics,
  generateBiglakeMetrics,
  generateCertificateManagerMetrics,
  generateBlockchainNodeEngineMetrics,
  generateNetappVolumesMetrics,
} from "./extendedServices.js";

const DEDICATED: Record<string, MetricGenerator> = {
  "compute-engine": generateComputeEngineMetrics,
  "sole-tenant-nodes": generateSoleTenantNodesMetrics,
  "spot-vms": generateSpotVmsMetrics,
  "shielded-vms": generateShieldedVmsMetrics,
  "confidential-computing": generateConfidentialComputingMetrics,
  "migrate-to-vms": generateMigrateToVmsMetrics,
  gke: generateGkeMetrics,
  "gke-autopilot": generateGkeMetrics,
  "config-connector": generateConfigConnectorMetrics,
  "cloud-lb": generateCloudLbMetrics,
  "serverless-neg": generateServerlessNegMetrics,
  "cloud-cdn": generateCloudCdnMetrics,
  "cloud-dns": generateCloudDnsMetrics,
  "cloud-armor": generateCloudArmorMetrics,
  "cloud-interconnect": generateCloudInterconnectMetrics,
  "cloud-nat": generateCloudNatMetrics,
  "cloud-vpn": generateCloudVpnMetrics,
  "cloud-router": generateCloudRouterMetrics,
  "vpc-flow": generateVpcFlowMetrics,
  "packet-mirroring": generatePacketMirroringMetrics,
  "network-service-tiers": generateNetworkServiceTiersMetrics,
  "cloud-kms": generateCloudKmsMetrics,
  "secret-manager": generateSecretManagerMetrics,
  "cloud-ids": generateCloudIdsMetrics,
  "binary-authorization": generateBinaryAuthorizationMetrics,
  "certificate-authority": generateCertificateAuthorityMetrics,
  "identity-aware-proxy": generateIdentityAwareProxyMetrics,
  "web-security-scanner": generateWebSecurityScannerMetrics,
  "web-risk": generateWebRiskMetrics,
  "recaptcha-enterprise": generateRecaptchaEnterpriseMetrics,
  "cloud-sql": generateCloudSqlMetrics,
  "cloud-spanner": generateCloudSpannerMetrics,
  bigtable: generateBigtableMetrics,
  firestore: generateFirestoreMetrics,
  alloydb: generateAlloyDbMetrics,
  memorystore: generateMemorystoreMetrics,
  pubsub: generatePubSubMetrics,
  dataflow: generateDataflowMetrics,
  bigquery: generateBigQueryMetrics,
  dataproc: generateDataprocMetrics,
  composer: generateComposerMetrics,
  "data-catalog": generateDataCatalogMetrics,
  "data-fusion": generateDataFusionMetrics,
  "database-migration": generateDatabaseMigrationMetrics,
  dataplex: generateDataplexMetrics,
  datastream: generateDatastreamMetrics,
  "analytics-hub": generateAnalyticsHubMetrics,
  looker: generateLookerMetrics,
  "natural-language": generateNaturalLanguageMetrics,
  "speech-to-text": generateSpeechToTextMetrics,
  "text-to-speech": generateTextToSpeechMetrics,
  translation: generateTranslationMetrics,
  "video-intelligence": generateVideoIntelligenceMetrics,
  "vision-ai": generateVisionAiMetrics,
  "recommendations-ai": generateRecommendationsAiMetrics,
  "retail-api": generateRetailApiMetrics,
  "document-ai": generateDocumentAiMetrics,
  "healthcare-api": generateHealthcareApiMetrics,
  dialogflow: generateDialogflowMetrics,
  "contact-center-ai": generateContactCenterAiMetrics,
  "cloud-functions": generateCloudFunctionsMetrics,
  "cloud-run": generateCloudRunMetrics,
  "app-engine": generateAppEngineMetrics,
  "cloud-tasks": generateCloudTasksMetrics,
  "cloud-storage": generateCloudStorageMetrics,
  "storage-transfer": generateStorageTransferMetrics,
  "vertex-ai": generateVertexAiMetrics,
  "vertex-ai-search": generateVertexAiSearchMetrics,
  gemini: generateGeminiMetrics,
  "cloud-run-jobs": generateCloudRunJobsMetrics,
  "cloud-scheduler": generateCloudSchedulerMetrics,
  "cloud-tpu": generateCloudTpuMetrics,
  "cloud-workstations": generateCloudWorkstationsMetrics,
  batch: generateBatchMetrics,
  "deployment-manager": generateDeploymentManagerMetrics,
  eventarc: generateEventarcMetrics,
  workflows: generateWorkflowsMetrics,
  firebase: generateFirebaseMetrics,
  "cloud-endpoints": generateCloudEndpointsMetrics,
  "api-gateway": generateApiGatewayMetrics,
  "api-hub": generateApiHubMetrics,
  "application-integration": generateApplicationIntegrationMetrics,
  "serverless-vpc-access": generateServerlessVpcAccessMetrics,
  "service-directory": generateServiceDirectoryMetrics,
  "private-service-connect": generatePrivateServiceConnectMetrics,
  "network-connectivity-center": generateNetworkConnectivityCenterMetrics,
  "network-intelligence-center": generateNetworkIntelligenceCenterMetrics,
  "traffic-director": generateTrafficDirectorMetrics,
  "cloud-audit-logs": generateCloudAuditLogsMetrics,
  "cloud-deploy": generateCloudDeployMetrics,
  "cloud-logging": generateCloudLoggingMetrics,
  "cloud-monitoring": generateCloudMonitoringMetrics,
  "cloud-trace": generateCloudTraceMetrics,
  "cloud-profiler": generateCloudProfilerMetrics,
  "cloud-identity": generateCloudIdentityMetrics,
  iam: generateIamMetrics,
  "org-policy": generateOrgPolicyMetrics,
  "resource-manager": generateResourceManagerMetrics,
  "essential-contacts": generateEssentialContactsMetrics,
  "error-reporting": generateErrorReportingMetrics,
  "assured-workloads": generateAssuredWorkloadsMetrics,
  "container-registry": generateContainerRegistryMetrics,
  "artifact-registry": generateArtifactRegistryMetrics,
  dlp: generateDlpMetrics,
  anthos: generateAnthosMetrics,
  "anthos-config-mgmt": generateAnthosConfigMgmtMetrics,
  "anthos-service-mesh": generateAnthosServiceMeshMetrics,
  "migrate-to-containers": generateMigrateToContainersMetrics,
  "security-command-center": generateSecurityCommandCenterMetrics,
  "security-operations": generateSecurityOperationsMetrics,
  "managed-ad": generateManagedAdMetrics,
  "pubsub-lite": generatePubsubLiteMetrics,
  "persistent-disk": generatePersistentDiskMetrics,
  filestore: generateFilestoreMetrics,
  "cloud-build": generateCloudBuildMetrics,
  "source-repositories": generateSourceRepositoriesMetrics,
  "iot-core": generateIotCoreMetrics,
  "gke-enterprise": generateGkeEnterpriseMetrics,
  automl: generateAutomlMetrics,
  "access-context-manager": generateAccessContextManagerMetrics,
  "active-assist": generateActiveAssistMetrics,
  apigee: generateApigeeMetrics,
  "backup-dr": generateBackupDrMetrics,
  "bare-metal": generateBareMetalMetrics,
  beyondcorp: generateBeyondcorpMetrics,
  billing: generateBillingMetrics,
  "cloud-asset-inventory": generateCloudAssetInventoryMetrics,
  "cloud-domains": generateCloudDomainsMetrics,
  "media-cdn": generateMediaCdnMetrics,
  transcoder: generateTranscoderMetrics,
  "vertex-ai-workbench": generateVertexAiWorkbenchMetrics,
  "vertex-ai-pipelines": generateVertexAiPipelinesMetrics,
  "vertex-ai-feature-store": generateVertexAiFeatureStoreMetrics,
  "vertex-ai-matching-engine": generateVertexAiMatchingEngineMetrics,
  "vertex-ai-tensorboard": generateVertexAiTensorboardMetrics,
  "vertex-ai-agent-builder": generateVertexAiAgentBuilderMetrics,
  "vmware-engine": generateVmwareEngineMetrics,
  "colab-enterprise": generateColabEnterpriseMetrics,
  "distributed-cloud": generateDistributedCloudMetrics,
  parallelstore: generateParallelstoreMetrics,
  dataform: generateDataformMetrics,
  biglake: generateBiglakeMetrics,
  "certificate-manager": generateCertificateManagerMetrics,
  "blockchain-node-engine": generateBlockchainNodeEngineMetrics,
  "netapp-volumes": generateNetappVolumesMetrics,
};

function metricGenForId(id: string): MetricGenerator {
  const gen = DEDICATED[id];
  if (!gen) throw new Error(`No dedicated GCP metric generator for: ${id}`);
  return gen;
}

/** Parent id → variant ids (random pick each emission). */
const METRIC_MERGE_VARIANTS: Record<string, string[]> = {
  "compute-engine": [
    "compute-engine",
    "sole-tenant-nodes",
    "spot-vms",
    "shielded-vms",
    "confidential-computing",
    "migrate-to-vms",
  ],
  gke: ["gke", "config-connector"],
  "vpc-flow": ["vpc-flow", "packet-mirroring", "network-service-tiers"],
  "cloud-lb": ["cloud-lb", "serverless-neg"],
  "cloud-storage": ["cloud-storage", "storage-transfer"],
  "vertex-ai": ["vertex-ai", "vertex-ai-search"],
  "cloud-build": ["cloud-build", "source-repositories"],
  "cloud-monitoring": ["cloud-monitoring", "cloud-trace", "cloud-profiler"],
  "api-gateway": ["api-gateway", "api-hub"],
};

const BASE: Record<string, MetricGenerator> = Object.fromEntries(
  [...GCP_METRICS_SUPPORTED_SERVICE_IDS].sort().map((id) => [id, metricGenForId(id)])
);

export const GCP_METRICS_GENERATORS: Record<string, MetricGenerator> = { ...BASE };

for (const [parent, variantIds] of Object.entries(METRIC_MERGE_VARIANTS)) {
  if (!GCP_METRICS_GENERATORS[parent]) continue;
  const gens = variantIds.map((vid) => metricGenForId(vid));
  GCP_METRICS_GENERATORS[parent] = mergeGcpMetricVariants(gens);
  for (const vid of variantIds) {
    if (vid !== parent) delete GCP_METRICS_GENERATORS[vid];
  }
}
