import { AZURE_METRICS_SUPPORTED_SERVICE_IDS } from "../../data/elasticMaps.js";
import type { MetricGenerator } from "../../../aws/generators/types.js";
import {
  generateIotHubMetrics,
  generateLogicAppsMetrics,
  generateApiManagementMetrics,
  generateEventGridMetrics,
  generateSynapseWorkspaceMetrics,
  generateDatabricksMetrics,
  generateCosmosDbDedicatedMetrics,
  generateEventHubsDedicatedMetrics,
  generateAppServiceDedicatedMetrics,
  generateFunctionsDedicatedMetrics,
  generateAksDedicatedMetrics,
  generateBlobStorageDedicatedMetrics,
  generateSqlDatabaseDedicatedMetrics,
  generateCacheForRedisDedicatedMetrics,
  generateLoadBalancerDedicatedMetrics,
  generateOpenAiDedicatedMetrics,
} from "./dedicated.js";
import {
  generateActivityLogDedicatedMetrics,
  generateAdvisorDedicatedMetrics,
  generateAnalysisServicesDedicatedMetrics,
  generateAppConfigurationDedicatedMetrics,
  generateAutomationAccountDedicatedMetrics,
  generateBackupDedicatedMetrics,
  generateBlueprintsDedicatedMetrics,
  generateBotServiceDedicatedMetrics,
  generateCdnDedicatedMetrics,
  generateCognitiveServicesDedicatedMetrics,
  generateCommunicationServicesDedicatedMetrics,
  generateCostManagementDedicatedMetrics,
  generateDataBoxDedicatedMetrics,
  generateDataFactoryDedicatedMetrics,
  generateDatabaseForMariadbDedicatedMetrics,
  generateDatabaseForMysqlDedicatedMetrics,
  generateDatabaseForPostgresqlDedicatedMetrics,
  generateDeploymentEnvironmentsDedicatedMetrics,
  generateDevcenterDedicatedMetrics,
  generateDeviceProvisioningDedicatedMetrics,
  generateDigitalTwinsDedicatedMetrics,
  generateDocumentIntelligenceDedicatedMetrics,
  generateFileStorageDedicatedMetrics,
  generateHdinsightDedicatedMetrics,
  generateHpcCacheDedicatedMetrics,
} from "./dedicatedData.js";
import {
  generateAiSearchDedicatedMetrics,
  generateArcDedicatedMetrics,
  generateAttestationDedicatedMetrics,
  generateBastionDedicatedMetrics,
  generateConfidentialLedgerDedicatedMetrics,
  generateIotCentralDedicatedMetrics,
  generateLabServicesDedicatedMetrics,
  generateManagedIdentityDedicatedMetrics,
  generateMapsDedicatedMetrics,
  generateMediaServicesDedicatedMetrics,
  generateMigrateDedicatedMetrics,
  generateMonitorDedicatedMetrics,
  generateNetworkSecurityGroupsDedicatedMetrics,
  generateNetworkWatcherDedicatedMetrics,
  generateNotificationHubsDedicatedMetrics,
  generateOracleOnAzureDedicatedMetrics,
  generatePolicyDedicatedMetrics,
  generatePowerBiEmbeddedDedicatedMetrics,
  generatePrivateDnsDedicatedMetrics,
  generatePrivateLinkDedicatedMetrics,
  generatePurviewDedicatedMetrics,
  generateQueueStorageDedicatedMetrics,
  generateRelayDedicatedMetrics,
  generateResourceGraphDedicatedMetrics,
} from "./dedicatedAiSecurity.js";
import {
  generateApplicationGatewayDedicatedExtendedMetrics,
  generateAzureFirewallDedicatedExtendedMetrics,
  generateBatchDedicatedExtendedMetrics,
  generateContainerAppsDedicatedExtendedMetrics,
  generateContainerInstancesDedicatedExtendedMetrics,
  generateDdosProtectionDedicatedExtendedMetrics,
  generateDefenderForCloudDedicatedExtendedMetrics,
  generateEntraIdDedicatedExtendedMetrics,
  generateExpressRouteCircuitDedicatedExtendedMetrics,
  generateExpressRouteGatewayDedicatedExtendedMetrics,
  generateFirewallPolicyDedicatedExtendedMetrics,
  generateFrontDoorDedicatedExtendedMetrics,
  generateKeyVaultDedicatedExtendedMetrics,
  generateKubernetesFleetDedicatedExtendedMetrics,
  generateLoadTestingDedicatedExtendedMetrics,
  generateMachineLearningDedicatedExtendedMetrics,
  generateNatGatewayDedicatedExtendedMetrics,
  generateSentinelDedicatedExtendedMetrics,
  generateServiceBusDedicatedExtendedMetrics,
  generateSqlManagedInstanceDedicatedExtendedMetrics,
  generateVirtualMachinesDedicatedExtendedMetrics,
  generateVirtualNetworkDedicatedExtendedMetrics,
  generateVmScaleSetsDedicatedExtendedMetrics,
  generateVpnClientDedicatedExtendedMetrics,
  generateVpnGatewayDedicatedExtendedMetrics,
} from "./dedicatedExtended.js";
import {
  generateApiCenterDedicatedRemainingMetrics,
  generateAzureStackDedicatedRemainingMetrics,
  generateDataLakeStorageDedicatedRemainingMetrics,
  generateM365DedicatedRemainingMetrics,
  generateMicrosoftFabricDedicatedRemainingMetrics,
  generateNetappFilesDedicatedRemainingMetrics,
  generateRouteServerDedicatedRemainingMetrics,
  generateSapOnAzureDedicatedRemainingMetrics,
  generateSignalrDedicatedRemainingMetrics,
  generateSiteRecoveryDedicatedRemainingMetrics,
  generateSpeechDedicatedRemainingMetrics,
  generateSpringAppsDedicatedRemainingMetrics,
  generateStaticWebAppsDedicatedRemainingMetrics,
  generateStorageSyncDedicatedRemainingMetrics,
  generateStreamAnalyticsDedicatedRemainingMetrics,
  generateTableStorageDedicatedRemainingMetrics,
  generateTimeSeriesInsightsDedicatedRemainingMetrics,
  generateTrafficManagerDedicatedRemainingMetrics,
  generateTranslatorDedicatedRemainingMetrics,
  generateVirtualWanDedicatedRemainingMetrics,
  generateVisionDedicatedRemainingMetrics,
  generateVmwareSolutionDedicatedRemainingMetrics,
  generateWafPolicyDedicatedRemainingMetrics,
} from "./dedicatedRemaining.js";
import {
  generateAcrDedicatedFinalMetrics,
  generateCapacityReservationDedicatedFinalMetrics,
  generateComputeGalleryDedicatedFinalMetrics,
  generateConfidentialVmDedicatedFinalMetrics,
  generateDedicatedHostDedicatedFinalMetrics,
  generateImageBuilderDedicatedFinalMetrics,
  generatePipelineDedicatedFinalMetrics,
  generateProximityPlacementDedicatedFinalMetrics,
} from "./dedicatedFinal.js";
import {
  generateAiFoundryDedicatedMetrics,
  generateApplicationInsightsDedicatedMetrics,
  generateDataExplorerDedicatedMetrics,
  generateDedicatedHsmDedicatedMetrics,
  generateDnsPrivateResolverDedicatedMetrics,
  generateElasticSanDedicatedMetrics,
  generateManagedGrafanaDedicatedMetrics,
  generateManagedPrometheusDedicatedMetrics,
  generateVideoIndexerDedicatedMetrics,
  generateVirtualDesktopDedicatedMetrics,
} from "./azurePlatformServicesExtendedMetrics.js";
import { mergeAzureMetricVariants } from "../mergeHelpers.js";
import { M365_METRICS_GENERATORS } from "../../../m365/generators/metrics/index.js";
import { M365_METRIC_SERVICE_IDS_FOR_AZURE } from "../../../cloud/m365Config.js";

const DEDICATED_METRICS: Record<string, MetricGenerator> = {
  "iot-hub": generateIotHubMetrics,
  "logic-apps": generateLogicAppsMetrics,
  "api-management": generateApiManagementMetrics,
  "event-grid": generateEventGridMetrics,
  "synapse-workspace": generateSynapseWorkspaceMetrics,
  databricks: generateDatabricksMetrics,
  "cosmos-db": generateCosmosDbDedicatedMetrics,
  "event-hubs": generateEventHubsDedicatedMetrics,
  "app-service": generateAppServiceDedicatedMetrics,
  functions: generateFunctionsDedicatedMetrics,
  aks: generateAksDedicatedMetrics,
  "blob-storage": generateBlobStorageDedicatedMetrics,
  "sql-database": generateSqlDatabaseDedicatedMetrics,
  "cache-for-redis": generateCacheForRedisDedicatedMetrics,
  "load-balancer": generateLoadBalancerDedicatedMetrics,
  openai: generateOpenAiDedicatedMetrics,
  "application-gateway": generateApplicationGatewayDedicatedExtendedMetrics,
  "azure-firewall": generateAzureFirewallDedicatedExtendedMetrics,
  "container-apps": generateContainerAppsDedicatedExtendedMetrics,
  "container-instances": generateContainerInstancesDedicatedExtendedMetrics,
  batch: generateBatchDedicatedExtendedMetrics,
  "ddos-protection": generateDdosProtectionDedicatedExtendedMetrics,
  "expressroute-circuit": generateExpressRouteCircuitDedicatedExtendedMetrics,
  "expressroute-gateway": generateExpressRouteGatewayDedicatedExtendedMetrics,
  "front-door": generateFrontDoorDedicatedExtendedMetrics,
  "firewall-policy": generateFirewallPolicyDedicatedExtendedMetrics,
  "route-server": generateRouteServerDedicatedRemainingMetrics,
  "sap-on-azure": generateSapOnAzureDedicatedRemainingMetrics,
  signalr: generateSignalrDedicatedRemainingMetrics,
  "site-recovery": generateSiteRecoveryDedicatedRemainingMetrics,
  speech: generateSpeechDedicatedRemainingMetrics,
  "spring-apps": generateSpringAppsDedicatedRemainingMetrics,
  stack: generateAzureStackDedicatedRemainingMetrics,
  "static-web-apps": generateStaticWebAppsDedicatedRemainingMetrics,
  "storage-sync": generateStorageSyncDedicatedRemainingMetrics,
  "stream-analytics": generateStreamAnalyticsDedicatedRemainingMetrics,
  "table-storage": generateTableStorageDedicatedRemainingMetrics,
  "time-series-insights": generateTimeSeriesInsightsDedicatedRemainingMetrics,
  "traffic-manager": generateTrafficManagerDedicatedRemainingMetrics,
  translator: generateTranslatorDedicatedRemainingMetrics,
  "virtual-wan": generateVirtualWanDedicatedRemainingMetrics,
  vision: generateVisionDedicatedRemainingMetrics,
  "vmware-solution": generateVmwareSolutionDedicatedRemainingMetrics,
  "waf-policy": generateWafPolicyDedicatedRemainingMetrics,
  "microsoft-fabric": generateMicrosoftFabricDedicatedRemainingMetrics,
  m365: generateM365DedicatedRemainingMetrics,
  "data-lake-storage": generateDataLakeStorageDedicatedRemainingMetrics,
  "netapp-files": generateNetappFilesDedicatedRemainingMetrics,
  "api-center": generateApiCenterDedicatedRemainingMetrics,
  "nat-gateway": generateNatGatewayDedicatedExtendedMetrics,
  "virtual-machines": generateVirtualMachinesDedicatedExtendedMetrics,
  "virtual-network": generateVirtualNetworkDedicatedExtendedMetrics,
  "vm-scale-sets": generateVmScaleSetsDedicatedExtendedMetrics,
  "vpn-client": generateVpnClientDedicatedExtendedMetrics,
  "vpn-gateway": generateVpnGatewayDedicatedExtendedMetrics,
  "key-vault": generateKeyVaultDedicatedExtendedMetrics,
  "entra-id": generateEntraIdDedicatedExtendedMetrics,
  "kubernetes-fleet": generateKubernetesFleetDedicatedExtendedMetrics,
  "service-bus": generateServiceBusDedicatedExtendedMetrics,
  "sql-managed-instance": generateSqlManagedInstanceDedicatedExtendedMetrics,
  "load-testing": generateLoadTestingDedicatedExtendedMetrics,
  "machine-learning": generateMachineLearningDedicatedExtendedMetrics,
  sentinel: generateSentinelDedicatedExtendedMetrics,
  "defender-for-cloud": generateDefenderForCloudDedicatedExtendedMetrics,
  "activity-log": generateActivityLogDedicatedMetrics,
  advisor: generateAdvisorDedicatedMetrics,
  "analysis-services": generateAnalysisServicesDedicatedMetrics,
  "app-configuration": generateAppConfigurationDedicatedMetrics,
  "automation-account": generateAutomationAccountDedicatedMetrics,
  backup: generateBackupDedicatedMetrics,
  blueprints: generateBlueprintsDedicatedMetrics,
  "bot-service": generateBotServiceDedicatedMetrics,
  cdn: generateCdnDedicatedMetrics,
  "cognitive-services": generateCognitiveServicesDedicatedMetrics,
  "communication-services": generateCommunicationServicesDedicatedMetrics,
  "cost-management": generateCostManagementDedicatedMetrics,
  "data-box": generateDataBoxDedicatedMetrics,
  "data-factory": generateDataFactoryDedicatedMetrics,
  "database-for-mariadb": generateDatabaseForMariadbDedicatedMetrics,
  "database-for-mysql": generateDatabaseForMysqlDedicatedMetrics,
  "database-for-postgresql": generateDatabaseForPostgresqlDedicatedMetrics,
  "deployment-environments": generateDeploymentEnvironmentsDedicatedMetrics,
  devcenter: generateDevcenterDedicatedMetrics,
  "device-provisioning": generateDeviceProvisioningDedicatedMetrics,
  "digital-twins": generateDigitalTwinsDedicatedMetrics,
  "document-intelligence": generateDocumentIntelligenceDedicatedMetrics,
  "file-storage": generateFileStorageDedicatedMetrics,
  hdinsight: generateHdinsightDedicatedMetrics,
  "hpc-cache": generateHpcCacheDedicatedMetrics,
  "ai-search": generateAiSearchDedicatedMetrics,
  arc: generateArcDedicatedMetrics,
  attestation: generateAttestationDedicatedMetrics,
  bastion: generateBastionDedicatedMetrics,
  "confidential-ledger": generateConfidentialLedgerDedicatedMetrics,
  "iot-central": generateIotCentralDedicatedMetrics,
  "lab-services": generateLabServicesDedicatedMetrics,
  "managed-identity": generateManagedIdentityDedicatedMetrics,
  maps: generateMapsDedicatedMetrics,
  "media-services": generateMediaServicesDedicatedMetrics,
  migrate: generateMigrateDedicatedMetrics,
  monitor: generateMonitorDedicatedMetrics,
  "network-security-groups": generateNetworkSecurityGroupsDedicatedMetrics,
  "network-watcher": generateNetworkWatcherDedicatedMetrics,
  "notification-hubs": generateNotificationHubsDedicatedMetrics,
  "oracle-on-azure": generateOracleOnAzureDedicatedMetrics,
  policy: generatePolicyDedicatedMetrics,
  "power-bi-embedded": generatePowerBiEmbeddedDedicatedMetrics,
  "private-dns": generatePrivateDnsDedicatedMetrics,
  "private-link": generatePrivateLinkDedicatedMetrics,
  purview: generatePurviewDedicatedMetrics,
  "queue-storage": generateQueueStorageDedicatedMetrics,
  relay: generateRelayDedicatedMetrics,
  "resource-graph": generateResourceGraphDedicatedMetrics,
  acr: generateAcrDedicatedFinalMetrics,
  "compute-gallery": generateComputeGalleryDedicatedFinalMetrics,
  "image-builder": generateImageBuilderDedicatedFinalMetrics,
  pipeline: generatePipelineDedicatedFinalMetrics,
  "dedicated-host": generateDedicatedHostDedicatedFinalMetrics,
  "capacity-reservation": generateCapacityReservationDedicatedFinalMetrics,
  "proximity-placement": generateProximityPlacementDedicatedFinalMetrics,
  "confidential-vm": generateConfidentialVmDedicatedFinalMetrics,
  "ai-foundry": generateAiFoundryDedicatedMetrics,
  "application-insights": generateApplicationInsightsDedicatedMetrics,
  "data-explorer": generateDataExplorerDedicatedMetrics,
  "dedicated-hsm": generateDedicatedHsmDedicatedMetrics,
  "dns-private-resolver": generateDnsPrivateResolverDedicatedMetrics,
  "elastic-san": generateElasticSanDedicatedMetrics,
  "managed-grafana": generateManagedGrafanaDedicatedMetrics,
  "managed-prometheus": generateManagedPrometheusDedicatedMetrics,
  "video-indexer": generateVideoIndexerDedicatedMetrics,
  "virtual-desktop": generateVirtualDesktopDedicatedMetrics,
};

function metricGenForId(id: string): MetricGenerator {
  const gen = DEDICATED_METRICS[id];
  if (!gen) {
    throw new Error(`Missing dedicated Azure metric generator for service id: ${id}`);
  }
  return gen;
}

const METRIC_MERGE_VARIANTS: Record<string, string[]> = {
  "virtual-machines": [
    "virtual-machines",
    "dedicated-host",
    "capacity-reservation",
    "proximity-placement",
    "confidential-vm",
  ],
  "front-door": ["front-door", "cdn"],
};

const BASE: Record<string, MetricGenerator> = Object.fromEntries(
  [...AZURE_METRICS_SUPPORTED_SERVICE_IDS]
    .sort()
    .map((id) => [
      id,
      M365_METRIC_SERVICE_IDS_FOR_AZURE.has(id) ? M365_METRICS_GENERATORS[id]! : metricGenForId(id),
    ])
);

export const AZURE_METRICS_GENERATORS: Record<string, MetricGenerator> = { ...BASE };

for (const [parent, variantIds] of Object.entries(METRIC_MERGE_VARIANTS)) {
  if (!AZURE_METRICS_GENERATORS[parent]) continue;
  const gens = variantIds.map((vid) => metricGenForId(vid));
  AZURE_METRICS_GENERATORS[parent] = mergeAzureMetricVariants(gens);
  for (const vid of variantIds) {
    if (vid !== parent) delete AZURE_METRICS_GENERATORS[vid];
  }
}
