/**
 * Central registry of all AWS service log generators.
 * Each key is a service id (e.g. "lambda", "s3"); each value is a function (ts: string, er: number) => doc.
 * Used by the UI and by scripts/export-samples.mjs.
 * @module aws/generators/index
 */

import {
  generateLambdaLog,
  generateApiGatewayLog,
  generateAppSyncLog,
  generateAppRunnerLog,
  generateFargateLog,
} from "./serverless.js";
import {
  generateEc2Log,
  generateEcsLog,
  generateEksLog,
  generateBatchLog,
  generateBeanstalkLog,
  generateEcrLog,
  generateAutoScalingLog,
  generateImageBuilderLog,
  generateOutpostsLog,
  generateWavelengthLog,
  generateMainframeModernizationLog,
  generateParallelComputingLog,
  generateEvsLog,
  generateSimSpaceWeaverLog,
} from "./compute.js";
import {
  generateAlbLog,
  generateNlbLog,
  generateCloudFrontLog,
  generateWafLog,
  generateWafv2Log,
  generateRoute53Log,
  generateNetworkFirewallLog,
  generateShieldLog,
  generateGlobalAcceleratorLog,
  generateTransitGatewayLog,
  generateDirectConnectLog,
  generateVpnLog,
  generatePrivateLinkLog,
  generateNetworkManagerLog,
  generateNatGatewayLog,
  generateVpcFlowLog,
  generateVpcLatticeLog,
  generateAppMeshLog,
  generateClientVpnLog,
  generateCloudMapLog,
  generateVpcIpamLog,
  generatePrivate5gLog,
} from "./networking.js";
import {
  generateGuardDutyLog,
  generateSecurityHubLog,
  generateMacieLog,
  generateInspectorLog,
  generateConfigLog,
  generateAccessAnalyzerLog,
  generateCognitoLog,
  generateKmsLog,
  generateSecretsManagerLog,
  generateAcmLog,
  generateIamIdentityCenterLog,
  generateDetectiveLog,
  generateCloudTrailLog,
  generateVerifiedAccessLog,
  generateSecurityLakeLog,
  generateSecurityFindingChain,
  generateCspmFindings,
  generateKspmFindings,
  generateIamPrivEscChain,
  generateDataExfilChain,
  generateSecurityIrLog,
  generateCloudHsmLog,
  generateAuditManagerLog,
  generateVerifiedPermissionsLog,
  generatePaymentCryptographyLog,
  generateArtifactLog,
  generateNetworkAccessAnalyzerLog,
  generateIncidentManagerLog,
} from "./security.js";
import { generateDataPipelineChain } from "./dataPipelineChain.js";
import { generateServiceNowCmdbLog } from "../../servicenow/generators/index.js";
import {
  generateS3Log,
  generateS3StorageLensLog,
  generateEbsLog,
  generateEfsLog,
  generateFsxLog,
  generateDataSyncLog,
  generateBackupLog,
  generateStorageGatewayLog,
} from "./storage.js";
import {
  generateDynamoDbLog,
  generateElastiCacheLog,
  generateRedshiftLog,
  generateOpenSearchLog,
  generateDocumentDbLog,
  generateAuroraLog,
  generateNeptuneLog,
  generateTimestreamLog,
  generateQldbLog,
  generateKeyspacesLog,
  generateMemoryDbLog,
  generateRdsLog,
  generateDaxLog,
  generateNeptuneAnalyticsLog,
  generateAuroraDsqlLog,
} from "./databases.js";
import {
  generateKinesisStreamsLog,
  generateFirehoseLog,
  generateKinesisAnalyticsLog,
  generateMskLog,
  generateSqsLog,
  generateSnsLog,
  generateAmazonMqLog,
  generateEventBridgeLog,
  generateStepFunctionsLog,
  generateMskConnectLog,
  generateEndUserMessagingLog,
} from "./streaming.js";
import {
  generateCodeBuildLog,
  generateCodePipelineLog,
  generateCodeDeployLog,
  generateCodeCommitLog,
  generateCodeArtifactLog,
  generateAmplifyLog,
  generateXRayLog,
  generateCodeGuruLog,
  generateCodeCatalystLog,
  generateDeviceFarmLog,
  generateProtonLog,
  generateQDeveloperLog,
  generateCloudShellLog,
  generateCloud9Log,
  generateRoboMakerLog,
} from "./devtools.js";
import {
  generateEmrLog,
  generateGlueLog,
  generateAthenaLog,
  generateLakeFormationLog,
  generateQuickSightLog,
  generateDataBrewLog,
  generateAppFlowLog,
  generateMwaaLog,
  generateCleanRoomsLog,
  generateDataZoneLog,
  generateEntityResolutionLog,
  generateDataExchangeLog,
  generateAppFabricLog,
  generateB2biLog,
} from "./analytics.js";
import {
  generateSageMakerLog,
  generateBedrockLog,
  generateBedrockAgentLog,
  generateRekognitionLog,
  generateTextractLog,
  generateComprehendLog,
  generateComprehendMedicalLog,
  generateTranslateLog,
  generateTranscribeLog,
  generatePollyLog,
  generateForecastLog,
  generatePersonalizeLog,
  generateLexLog,
  generateLookoutMetricsLog,
  generateQBusinessLog,
  generateKendraLog,
  generateA2iLog,
  generateHealthLakeLog,
  generateNovaLog,
  generateLookoutVisionLog,
  generateHealthOmicsLog,
  generateBedrockDataAutomationLog,
  generateLookoutEquipmentLog,
  generateMonitronLog,
} from "./ml.js";
import {
  generateIotCoreLog,
  generateIotGreengrassLog,
  generateIotAnalyticsLog,
  generateIotDefenderLog,
  generateIotEventsLog,
  generateIotSiteWiseLog,
  generateIotTwinMakerLog,
  generateIotFleetWiseLog,
  generateGroundStationLog,
  generateKinesisVideoLog,
  generatePanoramaLog,
  generateFreeRtosLog,
} from "./iot.js";
import {
  generateCloudFormationLog,
  generateSsmLog,
  generateCloudWatchAlarmsLog,
  generateHealthLog,
  generateTrustedAdvisorLog,
  generateControlTowerLog,
  generateOrganizationsLog,
  generateServiceCatalogLog,
  generateServiceQuotasLog,
  generateComputeOptimizerLog,
  generateBudgetsLog,
  generateBillingLog,
  generateDmsLog,
  generateFisLog,
  generateManagedGrafanaLog,
  generateSupplyChainLog,
  generateArcLog,
  generateAppConfigLog,
  generateDrsLog,
  generateLicenseManagerLog,
  generateChatbotLog,
  generateCloudWatchRumLog,
} from "./management.js";
import {
  generateWorkSpacesLog,
  generateConnectLog,
  generateAppStreamLog,
  generateGameLiftLog,
  generateSesLog,
  generatePinpointLog,
  generateTransferFamilyLog,
  generateLightsailLog,
  generateFraudDetectorLog,
  generateLocationServiceLog,
  generateMediaConvertLog,
  generateMediaLiveLog,
  generateManagedBlockchainLog,
  generateResilienceHubLog,
  generateRamLog,
  generateMigrationHubLog,
  generateDevOpsGuruLog,
  generateDeadlineCloudLog,
  generateChimeSdkLog,
  generateWorkMailLog,
  generateWickrLog,
} from "./enduser.js";

const GENERATORS = {
  // Group 1 — Serverless & Core
  lambda: generateLambdaLog,
  apigateway: generateApiGatewayLog,
  vpc: generateVpcFlowLog,
  cloudtrail: generateCloudTrailLog,
  rds: generateRdsLog,
  ecs: generateEcsLog,
  // Group 2 — Compute & Containers
  ec2: generateEc2Log,
  outposts: generateOutpostsLog,
  wavelength: generateWavelengthLog,
  eks: generateEksLog,
  apprunner: generateAppRunnerLog,
  batch: generateBatchLog,
  elasticbeanstalk: generateBeanstalkLog,
  ecr: generateEcrLog,
  fargate: generateFargateLog,
  autoscaling: generateAutoScalingLog,
  imagebuilder: generateImageBuilderLog,
  mainframemodernization: generateMainframeModernizationLog,
  parallelcomputing: generateParallelComputingLog,
  evs: generateEvsLog,
  simspaceweaver: generateSimSpaceWeaverLog,
  // Group 3 — Networking & CDN
  alb: generateAlbLog,
  cloudfront: generateCloudFrontLog,
  waf: generateWafLog,
  route53: generateRoute53Log,
  networkfirewall: generateNetworkFirewallLog,
  shield: generateShieldLog,
  nlb: generateNlbLog,
  globalaccelerator: generateGlobalAcceleratorLog,
  transitgateway: generateTransitGatewayLog,
  directconnect: generateDirectConnectLog,
  vpn: generateVpnLog,
  privatelink: generatePrivateLinkLog,
  networkmanager: generateNetworkManagerLog,
  natgateway: generateNatGatewayLog,
  vpclattice: generateVpcLatticeLog,
  appmesh: generateAppMeshLog,
  clientvpn: generateClientVpnLog,
  cloudmap: generateCloudMapLog,
  vpcipam: generateVpcIpamLog,
  private5g: generatePrivate5gLog,
  // Group 4 — Security & Compliance
  guardduty: generateGuardDutyLog,
  securityhub: generateSecurityHubLog,
  macie: generateMacieLog,
  inspector: generateInspectorLog,
  config: generateConfigLog,
  accessanalyzer: generateAccessAnalyzerLog,
  cognito: generateCognitoLog,
  kms: generateKmsLog,
  secretsmanager: generateSecretsManagerLog,
  acm: generateAcmLog,
  identitycenter: generateIamIdentityCenterLog,
  detective: generateDetectiveLog,
  verifiedaccess: generateVerifiedAccessLog,
  securitylake: generateSecurityLakeLog,
  "security-chain": generateSecurityFindingChain,
  cspm: generateCspmFindings,
  kspm: generateKspmFindings,
  "iam-privesc-chain": generateIamPrivEscChain,
  "data-exfil-chain": generateDataExfilChain,
  "data-pipeline-chain": generateDataPipelineChain,
  securityir: generateSecurityIrLog,
  cloudhsm: generateCloudHsmLog,
  auditmanager: generateAuditManagerLog,
  verifiedpermissions: generateVerifiedPermissionsLog,
  paymentcryptography: generatePaymentCryptographyLog,
  artifact: generateArtifactLog,
  networkaccessanalyzer: generateNetworkAccessAnalyzerLog,
  incidentmanager: generateIncidentManagerLog,
  // Group 5 — Storage
  s3: generateS3Log,
  storagelens: generateS3StorageLensLog,
  ebs: generateEbsLog,
  efs: generateEfsLog,
  fsx: generateFsxLog,
  datasync: generateDataSyncLog,
  backup: generateBackupLog,
  storagegateway: generateStorageGatewayLog,
  // Group 5 — Databases
  dynamodb: generateDynamoDbLog,
  elasticache: generateElastiCacheLog,
  redshift: generateRedshiftLog,
  opensearch: generateOpenSearchLog,
  docdb: generateDocumentDbLog,
  aurora: generateAuroraLog,
  neptune: generateNeptuneLog,
  timestream: generateTimestreamLog,
  qldb: generateQldbLog,
  dax: generateDaxLog,
  keyspaces: generateKeyspacesLog,
  memorydb: generateMemoryDbLog,
  neptuneanalytics: generateNeptuneAnalyticsLog,
  auroradsql: generateAuroraDsqlLog,
  // Group 6 — Streaming & Messaging
  kinesis: generateKinesisStreamsLog,
  firehose: generateFirehoseLog,
  msk: generateMskLog,
  sqs: generateSqsLog,
  eventbridge: generateEventBridgeLog,
  stepfunctions: generateStepFunctionsLog,
  sns: generateSnsLog,
  amazonmq: generateAmazonMqLog,
  appsync: generateAppSyncLog,
  kinesisanalytics: generateKinesisAnalyticsLog,
  mskconnect: generateMskConnectLog,
  endusermessaging: generateEndUserMessagingLog,
  // Group 7 — Developer & CI/CD
  codebuild: generateCodeBuildLog,
  codepipeline: generateCodePipelineLog,
  codedeploy: generateCodeDeployLog,
  xray: generateXRayLog,
  codecommit: generateCodeCommitLog,
  codeartifact: generateCodeArtifactLog,
  amplify: generateAmplifyLog,
  codeguru: generateCodeGuruLog,
  codecatalyst: generateCodeCatalystLog,
  devicefarm: generateDeviceFarmLog,
  qdeveloper: generateQDeveloperLog,
  cloudshell: generateCloudShellLog,
  cloud9: generateCloud9Log,
  robomaker: generateRoboMakerLog,
  // Group 8 — Analytics
  emr: generateEmrLog,
  glue: generateGlueLog,
  athena: generateAthenaLog,
  lakeformation: generateLakeFormationLog,
  quicksight: generateQuickSightLog,
  databrew: generateDataBrewLog,
  appflow: generateAppFlowLog,
  mwaa: generateMwaaLog,
  cleanrooms: generateCleanRoomsLog,
  datazone: generateDataZoneLog,
  entityresolution: generateEntityResolutionLog,
  dataexchange: generateDataExchangeLog,
  appfabric: generateAppFabricLog,
  b2bi: generateB2biLog,
  // Group 9 — AI & ML
  sagemaker: generateSageMakerLog,
  bedrock: generateBedrockLog,
  bedrockagent: generateBedrockAgentLog,
  rekognition: generateRekognitionLog,
  textract: generateTextractLog,
  comprehend: generateComprehendLog,
  translate: generateTranslateLog,
  transcribe: generateTranscribeLog,
  polly: generatePollyLog,
  forecast: generateForecastLog,
  personalize: generatePersonalizeLog,
  lex: generateLexLog,
  qbusiness: generateQBusinessLog,
  kendra: generateKendraLog,
  a2i: generateA2iLog,
  healthlake: generateHealthLakeLog,
  nova: generateNovaLog,
  lookoutvision: generateLookoutVisionLog,
  healthomics: generateHealthOmicsLog,
  bedrockdataautomation: generateBedrockDataAutomationLog,
  lookoutequipment: generateLookoutEquipmentLog,
  monitron: generateMonitronLog,
  // Group 10 — IoT
  iotcore: generateIotCoreLog,
  greengrass: generateIotGreengrassLog,
  iotanalytics: generateIotAnalyticsLog,
  iottwinmaker: generateIotTwinMakerLog,
  iotfleetwise: generateIotFleetWiseLog,
  groundstation: generateGroundStationLog,
  kinesisvideo: generateKinesisVideoLog,
  panorama: generatePanoramaLog,
  freertos: generateFreeRtosLog,
  // Group 11 — Management & Governance
  cloudformation: generateCloudFormationLog,
  ssm: generateSsmLog,
  cloudwatch: generateCloudWatchAlarmsLog,
  health: generateHealthLog,
  trustedadvisor: generateTrustedAdvisorLog,
  controltower: generateControlTowerLog,
  organizations: generateOrganizationsLog,
  dms: generateDmsLog,
  servicequotas: generateServiceQuotasLog,
  computeoptimizer: generateComputeOptimizerLog,
  ram: generateRamLog,
  resiliencehub: generateResilienceHubLog,
  migrationhub: generateMigrationHubLog,
  servicecatalog: generateServiceCatalogLog,
  budgets: generateBudgetsLog,
  billing: generateBillingLog,
  fis: generateFisLog,
  managedgrafana: generateManagedGrafanaLog,
  supplychain: generateSupplyChainLog,
  arc: generateArcLog,
  appconfig: generateAppConfigLog,
  drs: generateDrsLog,
  licensemanager: generateLicenseManagerLog,
  chatbot: generateChatbotLog,
  cloudwatchrum: generateCloudWatchRumLog,
  // Group 12 — Media & End User Computing
  mediaconvert: generateMediaConvertLog,
  medialive: generateMediaLiveLog,
  workspaces: generateWorkSpacesLog,
  connect: generateConnectLog,
  appstream: generateAppStreamLog,
  deadlinecloud: generateDeadlineCloudLog,
  chimesdkvoice: generateChimeSdkLog,
  workmail: generateWorkMailLog,
  wickr: generateWickrLog,
  // Group 13 — Messaging & Communications
  ses: generateSesLog,
  pinpoint: generatePinpointLog,
  // Group 14 — Additional Services
  transferfamily: generateTransferFamilyLog,
  lightsail: generateLightsailLog,
  frauddetector: generateFraudDetectorLog,
  lookoutmetrics: generateLookoutMetricsLog,
  comprehendmedical: generateComprehendMedicalLog,
  gamelift: generateGameLiftLog,
  locationservice: generateLocationServiceLog,
  managedblockchain: generateManagedBlockchainLog,
  devopsguru: generateDevOpsGuruLog,
  proton: generateProtonLog,
  iotevents: generateIotEventsLog,
  iotsitewise: generateIotSiteWiseLog,
  iotdefender: generateIotDefenderLog,
  wafv2: generateWafv2Log,
  // Cross-cloud ITSM
  servicenow_cmdb: generateServiceNowCmdbLog,
};

/**
 * Map of service id → generator function.
 * @type {Record<string, (ts: string, er: number) => Object>}
 */
export { GENERATORS };
