/**
 * Azure distributed trace scenarios (synthetic OTel / APM style).
 */

export const AZURE_TRACE_SERVICES = [
  { id: "app-service", label: "App Service — SQL & Redis" },
  { id: "functions", label: "Azure Functions — Event Hub → Cosmos" },
  { id: "aks", label: "AKS — HTTP → internal API" },
  { id: "service-bus-flow", label: "Service Bus — multi-hop workflow" },
  { id: "openai-chain", label: "OpenAI — embedding + completion" },
  { id: "data-factory-etl", label: "Data Factory — copy activity chain" },
  { id: "api-management", label: "API Management — backend latency" },
  { id: "workflow-cascading", label: "Cascading failure — Functions & Storage" },
  {
    id: "workflow-servicebus-fanout",
    label: "Service Bus fan-out — API Management → topic → 3 subscribers",
  },
  {
    id: "workflow-eventgrid-blob",
    label: "Event Grid + Blob — Function ETL → SQL warehouse",
  },
  {
    id: "workflow-durable-orchestration",
    label: "Durable Functions — HTTP starter → orchestration → 3 activities",
  },
  {
    id: "cosmos-db",
    label: "Cosmos DB",
    desc: "NoSQL document reads/writes — partition key routing spans via OTel SDK",
    group: "Single-Service",
  },
  {
    id: "sql-database",
    label: "Azure SQL Database",
    desc: "SQL query spans — connection pool + parameterized queries via OTel JDBC/ADO.NET",
    group: "Single-Service",
  },
  {
    id: "event-hubs",
    label: "Event Hubs",
    desc: "Producer/consumer traces — sendBatch and receiveMessages spans with partition context",
    group: "Single-Service",
  },
  {
    id: "key-vault",
    label: "Key Vault",
    desc: "Secret and key access spans — getSecret, listVersions via OTel SDK",
    group: "Single-Service",
  },
  {
    id: "logic-apps",
    label: "Logic Apps",
    desc: "Workflow action chain — trigger + HTTP/ServiceBus/notification action spans",
    group: "Single-Service",
  },
  {
    id: "cache-for-redis",
    label: "Cache for Redis",
    desc: "Redis client spans — GET, SET, MGET via StackExchange.Redis or equivalent",
    group: "Single-Service",
  },
  {
    id: "blob-storage",
    label: "Blob Storage",
    desc: "Blob metadata, download, and list operation spans",
    group: "Single-Service",
  },
  {
    id: "container-apps",
    label: "Container Apps",
    desc: "HTTP request handling with SQL and Service Bus downstream spans",
    group: "Single-Service",
  },
  {
    id: "machine-learning",
    label: "Machine Learning",
    desc: "Managed endpoint invocation — token acquisition and scoring spans",
    group: "Single-Service",
  },
  {
    id: "databricks",
    label: "Databricks",
    desc: "Spark job run — read, transform, and write stage spans",
    group: "Single-Service",
  },
  {
    id: "synapse-workspace",
    label: "Synapse workspace",
    desc: "Dedicated SQL pool queries and Spark notebook execution spans",
    group: "Single-Service",
  },
  {
    id: "openai",
    label: "Azure OpenAI",
    desc: "Embeddings and chat completion API spans",
    group: "Single-Service",
  },
  {
    id: "virtual-machines",
    label: "Virtual Machines",
    desc: "VM-hosted service request with local database and external HTTP spans",
    group: "Single-Service",
  },
  {
    id: "service-bus",
    label: "Service Bus",
    desc: "Queue receive, message processing, and complete spans",
    group: "Single-Service",
  },
  {
    id: "event-grid",
    label: "Event Grid",
    desc: "Event published → topic routing → subscription delivery → handler invocation",
    group: "Single-Service",
  },
  {
    id: "iot-hub",
    label: "IoT Hub",
    desc: "Device-to-cloud message → routing → endpoint delivery",
    group: "Single-Service",
  },
  {
    id: "entra-id",
    label: "Microsoft Entra ID",
    desc: "Login request → token validation → MFA check → token issuance",
    group: "Single-Service",
  },
  {
    id: "data-factory",
    label: "Data Factory",
    desc: "Pipeline run: trigger → copy/transform activity → sink write",
    group: "Single-Service",
  },
  {
    id: "load-balancer",
    label: "Load Balancer",
    desc: "Health probe → backend pool selection → NAT rule → forwarding",
    group: "Single-Service",
  },
  {
    id: "application-gateway",
    label: "Application Gateway",
    desc: "Request → WAF inspection → URL routing → backend forwarding",
    group: "Single-Service",
  },
  {
    id: "azure-firewall",
    label: "Azure Firewall",
    desc: "Packet → rule collection evaluation → allow/deny/DNAT action",
    group: "Single-Service",
  },
  {
    id: "stream-analytics",
    label: "Stream Analytics",
    desc: "Input event → query processing → output write → checkpoint",
    group: "Single-Service",
  },
  {
    id: "cognitive-services",
    label: "Azure AI / Cognitive Services",
    desc: "API call → model selection → inference → response assembly",
    group: "Single-Service",
  },
  {
    id: "ai-search",
    label: "Azure AI Search",
    desc: "Query → index lookup → scoring → result assembly",
    group: "Single-Service",
  },
  {
    id: "database-for-postgresql",
    label: "Azure Database for PostgreSQL",
    desc: "Connection → query parse → execution → result stream",
    group: "Single-Service",
  },
  {
    id: "sql-managed-instance",
    label: "Azure SQL Managed Instance",
    desc: "Connection → query optimization → execution → result set",
    group: "Single-Service",
  },
  {
    id: "sentinel",
    label: "Microsoft Sentinel",
    desc: "Log query → rule evaluation → incident creation → notification",
    group: "Single-Service",
  },
  {
    id: "defender-for-cloud",
    label: "Microsoft Defender for Cloud",
    desc: "Resource scan → policy evaluation → recommendation → alert",
    group: "Single-Service",
  },
  {
    id: "container-instances",
    label: "Container Instances",
    desc: "Create container group → pull image → start container → health probe",
    group: "Single-Service",
  },
] as const;
